In [8]:
import numpy as np

m = 2 #number of rows of A
n = 5 #number of columns of A
A = np. random.randn(m, n) #an m by n matrix of random numbers
print(A)
AtA = A.T @ A #A−transpose times A . . . n by n
AtA
AAt = A @ A.T #A−transpose times A . . . n by n
AAt

sizeA = A.shape
rankA = np.linalg.matrix_rank(A)

sizeAtA = AtA.shape
rankAtA = np.linalg.matrix_rank(AtA)

sizeAAt = AAt.shape
rankAAt = np.linalg.matrix_rank(AAt)

print (" size (A) =", sizeA )
print (" rank (A) =", rankA )
print (" size ( AtA ) =", sizeAtA )
print (" rank ( AtA ) =", rankAtA )
print (" size ( AAt ) =", sizeAAt )
print (" rank ( AAt ) =", rankAAt )

m = 3 #number of rows of A
n = 4 #number of columns of A
A = np. random.randn(m, n) #an m by n matrix of random numbers
print(A)
AtA = A.T @ A #A−transpose times A . . . n by n
AtA
AAt = A @ A.T #A−transpose times A . . . n by n
AAt

sizeA = A.shape
rankA = np.linalg.matrix_rank(A)

sizeAtA = AtA.shape
rankAtA = np.linalg.matrix_rank(AtA)

sizeAAt = AAt.shape
rankAAt = np.linalg.matrix_rank(AAt)

print (" size (A) =", sizeA )
print (" rank (A) =", rankA )
print (" size ( AtA ) =", sizeAtA )
print (" rank ( AtA ) =", rankAtA )
print (" size ( AAt ) =", sizeAAt )
print (" rank ( AAt ) =", rankAAt )

m = 3 #number of rows of A
n = 1 #number of columns of A
A = np. random.randn(m, n) #an m by n matrix of random numbers
print(A)
AtA = A.T @ A #A−transpose times A . . . n by n
AtA
AAt = A @ A.T #A−transpose times A . . . n by n
AAt

sizeA = A.shape
rankA = np.linalg.matrix_rank(A)

sizeAtA = AtA.shape
rankAtA = np.linalg.matrix_rank(AtA)

sizeAAt = AAt.shape
rankAAt = np.linalg.matrix_rank(AAt)

print (" size (A) =", sizeA )
print (" rank (A) =", rankA )
print (" size ( AtA ) =", sizeAtA )
print (" rank ( AtA ) =", rankAtA )
print (" size ( AAt ) =", sizeAAt )
print (" rank ( AAt ) =", rankAAt )

#the rank values make sense because
#For an 𝑚×𝑛 matrix the rank is equal to n if
#n < m and The n columns are linearly independent.

#For the case of m = 2
# what condition on A would result in the rank of AAT equaling 1?

m = 2 #number of rows of A
n = 5 #number of columns of A
A = np.random.randn(m, n) #an m by n matrix of random numbers
AAt = A @ A.T #A−transpose times A . . . n by n
AAt
sizeAAt = AAt.shape
rankAAt = np.linalg.matrix_rank(AAt)

#For a m×𝑛 where m = 2, the rank of AAT is 1 if the two rows of are linearly dependent
#that is if one is a scalar multiple of the other


[[ 0.31891264  1.40520496  0.36349394  0.11008263  0.62704457]
 [ 1.10139631  1.31471504 -2.37977483  0.49634907 -0.22025978]]
 size (A) = (2, 5)
 rank (A) = 2
 size ( AtA ) = (5, 5)
 rank ( AtA ) = 2
 size ( AAt ) = (2, 2)
 rank ( AAt ) = 2
[[-0.48672722  0.89981247 -0.5290606  -2.38158456]
 [-0.54242435  0.57291178 -1.18349562 -0.19158349]
 [-0.79680075  1.64840629 -0.92526732  0.36765996]]
 size (A) = (3, 4)
 rank (A) = 3
 size ( AtA ) = (4, 4)
 rank ( AtA ) = 3
 size ( AAt ) = (3, 3)
 rank ( AAt ) = 3
[[-0.68508492]
 [-1.10225196]
 [ 0.56918701]]
 size (A) = (3, 1)
 rank (A) = 1
 size ( AtA ) = (1, 1)
 rank ( AtA ) = 1
 size ( AAt ) = (3, 3)
 rank ( AAt ) = 1
